baseURL = "http://hugotestsite.markushylleberg.com"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"



[params]
extracssfiles          = [ "/css/override.css" ] 


[[menu.main]]
name                   = "Blog"
weight                 = 1
identifier             = "blog"
url                    = "/blog/"


[[menu.main]]
name                   = "About"
weight                 = 3
identifier             = "about"
url                    = "/about/"


[[menu.main]]
name                   = "Kontakt"
weight                 = 2
identifier             = "contact"
url                    = "/contact/"


[[menu.main]]
name                   = "Portfolio"
weight                 = 3
identifier             = "portfolio"
url                    = "/portfolio/"